### ISSUE TITLE
windows 10 多虚拟桌面切换不跟随

### ISSUE THREAD

**Issue by AngusWG** [DinoChan/OnePomodoro#78]
ctrl+win+d 创造新桌面
ctrl+win+方向键 切换桌面

此时软件不会在新桌面上显示

顺便提一个需求，希望能像[A pomodoro timer for gnome](https://gnomepomodoro.org/)一样，25分钟后会有个全局灰屏的操作提醒时间到了。

**Comment by AngusWG** [comment]
![image](https://user-images.githubusercontent.com/26385612/128835840-4151ac53-0703-4b4a-b97e-51a1f04b830a.png)

右键显示在全部桌面就好了。。

**Comment by DinoChan** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/26385612/128835840-4151ac53-0703-4b4a-b97e-51a1f04b830a.png)
> 
> 右键显示在全部桌面就好了。。

还有这招，厉害
